### ISSUE TITLE
使用卷积神经网络运行转录调控预测任务的模板文件链接失效？

### ISSUE THREAD

**Issue by panzhengsen** [zj-zhang/AMBER#21]
https://github.com/zj-zhang/AMBER/blob/master/templates/AmberDeepSea.py

**Comment by panzhengsen** [comment]
找到了，是AMBER-master\AMBER-master\examples\amber_deepsea.py吧

**Comment by zj-zhang** [comment]
Yes. Please let me know where the invalid URL is and I'll change it.

**Comment by panzhengsen** [comment]
失效的连接就是第一条评论中的链接

**Comment by panzhengsen** [comment]
https://github.com/zj-zhang/AMBER/blob/master/templates/AmberDeepSea.py
就是这个链接失效了，github提示404




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zj-zhang/AMBER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月10日(星期五) 晚上10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zj-zhang/AMBER] 使用卷积神经网络运行转录调控预测任务的模板文件链接失效？ (#21)





 
Yes. Please let me know where the invalid URL is and I'll change it.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by panzhengsen** [comment]
张老师您好，如果我的正集和负集序列文件分开放的，有什么办法可以把下面两个EncodedGenome拼接起来吗？
g1&nbsp;=&nbsp;EncodedGenome(input_file_nega,&nbsp;in_memory=False)
g2&nbsp;=&nbsp;EncodedGenome(input_file_posi,&nbsp;in_memory=False)

我尝试把g1.chrom_len_dict和g2.chrom_len_dict两个字典类型的数据用Merge函数拼接起来
def Merge(dict1, dict2):      res = {**dict1, **dict2}      return res 
     # 两个字典 dict1 = {'a': 10, 'b': 8}  dict2 = {'d': 6, 'c': 4}  dict3 = Merge(dict1, dict2)  print(dict3)


g = Merge(g1.chrom_len_dict, g2.chrom_len_dict)
但是这样g.ALPHABET_TO_ARRAY和g.data[chrom]等属性就丢失了

**Comment by zj-zhang** [comment]
Hello @panzhengsen ,
Could you please open a new issue for this and use English? The function you referred to might be developed by another lab member and he won't be able to understand here. Thank you.

**Comment by panzhengsen** [comment]
Thank you for replying to my message.
The positive set and negative set of my rna sequence are two files, but I noticed that all the sequences of deep_sea are in one file.
I used the following code：
g1&nbsp;=&nbsp;EncodedGenome(input_file_nega,&nbsp;in_memory=False)

g2&nbsp;=&nbsp;EncodedGenome(input_file_posi,&nbsp;in_memory=False)

Is there any way to combine g1 and g2 into one g?
It doesn’t matter if it’s difficult, I can also splice the two files into one file in Notepad, haha


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zj-zhang/AMBER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月12日(星期天) 晚上11:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zj-zhang/AMBER] 使用卷积神经网络运行转录调控预测任务的模板文件链接失效？ (#21)





 
Hello @panzhengsen ,
 Could you please open a new issue for this and use English? The function you referred to might be developed by another lab member and he won't be able to understand here. Thank you.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by panzhengsen** [comment]
Hello,
I encountered an error while training my data on the amber model. As follows:


['traindata', 'trainxdata']
['validdata', 'validxdata']
BUILDING
----------
controller = GeneralController
modeler = EnasCnnModelBuilder
knowledge = zero
reward = LossAucReward
manager = EnasManager
time budget set to: 24:00:00
env_type = EnasTrainEnv
&nbsp;Trial -1: Start training model with sample_arc...
Traceback (most recent call last):
&nbsp; File "amber_deepsea.py", line 124, in <module&gt;
&nbsp; &nbsp; amb.run()
&nbsp; File "/home/zhouss/AMBER/amber/wrapper.py", line 104, in run
&nbsp; &nbsp; self.env.train()
&nbsp; File "/home/zhouss/AMBER/amber/architect/trainEnv.py", line 418, in train
&nbsp; &nbsp; self.manager.get_rewards(trial=-i, model_arc=None, nsteps=warmup_nsteps)
&nbsp; File "/home/zhouss/AMBER/amber/architect/manager.py", line 544, in get_rewards
&nbsp; &nbsp; verbose=self.verbose,
&nbsp; File "/home/zhouss/AMBER/amber/modeler/child.py", line 743, in fit
&nbsp; &nbsp; prog = ", ".join(["%s=%.4f" % (name, hist.history[name][-1]) for name in to_print])
&nbsp; File "/home/zhouss/AMBER/amber/modeler/child.py", line 743, in <listcomp&gt;
&nbsp; &nbsp; prog = ", ".join(["%s=%.4f" % (name, hist.history[name][-1]) for name in to_print])
KeyError: 'loss'


I want to know how to solve this error. thank you for your reply

**Comment by panzhengsen** [comment]
I'm very sorry, I don't understand what you mean, could you elaborate on it?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zj-zhang/AMBER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 上午9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zj-zhang/AMBER] 使用卷积神经网络运行转录调控预测任务的模板文件链接失效？ (#21)





 
Reopened #21.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zj-zhang** [comment]
@panzhengsen No worries at all. Just re-opening the issue so I can better track it. 
In the future, it will be best to create a new GitHub issue to track a separate bug (in this case, since the one you have right now `KeyError: 'loss'` is different from `EncodedGenome`), instead commenting on a closed issue. 
I will look into this in the next few days. Thanks.

**Comment by panzhengsen** [comment]
ok
