### ISSUE TITLE
No module named 'amber.gui'

### ISSUE THREAD

**Issue by ShixiangWang** [zj-zhang/AMBER#26]
I install with pip and run with `amber`.

**Comment by zj-zhang** [comment]
@ShixiangWang The GUI is a command still under development. Please check the example usage here for running AMBER:
https://github.com/zj-zhang/AMBER/blob/master/examples/DeepSEA/amber_deepsea.py
Or by others on public benchmarking datasets:
https://github.com/rtu715/NAS-Bench-360/blob/main/AMBER/examples/amber_ecg.py
https://github.com/rtu715/NAS-Bench-360/blob/main/AMBER/examples/amber_satellite.py
Let me know if you have any questions.

**Comment by ShixiangWang** [comment]
@zj-zhang Thanks for your response.
