### ISSUE TITLE
What cause the error? KeyError: 'train_data '  

### ISSUE THREAD

**Issue by XuanrZhang** [zj-zhang/AMBER#30]
Hi zj-Zhang,

I would like to try amber tutorial.  The notebook at google colab didn't work, since colab does not support tensorFlow 1 code.

Then I installed amber and  tried the tutorial on linux server. but stuck on amber search step. 
I use *.mat dataset downloaded from  http://deepsea.princeton.edu/help/. 
Is there any suggestion to solve it?

---------------------errror message below ---------------------------
(amber) [bzhang4@venus21 AMBER]$ python  ~/Downloads/Data/tutorial.py
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0815 21:11:01.403670 46966903606976 deprecation_wrapper.py:119] From /home/bzhang4/Downloads/AMBER/amber/wrapper.py:11: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

/home/bzhang4/anaconda3/envs/amber/lib/python3.7/site-packages/ipykernel/comm/comm.py:9: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  from ipykernel.kernelbase import Kernel
['__header__', '__version__', '__globals__', 'validdata', 'validxdata']
['__header__', '__version__', '__globals__', 'testdata', 'testxdata']
BUILDING
----------
controller = GeneralController
modeler = EnasCnnModelBuilder
knowledge = zero
reward = LossAucReward
Traceback (most recent call last):
  File "/home/bzhang4/Downloads/Data/tutorial.py", line 154, in <module>
    amb = Amber(types=type_dict, specs=specs)
  File "/home/bzhang4/Downloads/AMBER/amber/wrapper.py", line 81, in __init__
    self.from_dict(specs)
  File "/home/bzhang4/Downloads/AMBER/amber/wrapper.py", line 112, in from_dict
    **d['manager']['params'])
  File "/home/bzhang4/Downloads/AMBER/amber/getter.py", line 317, in get_manager
    *args,
KeyError: 'train_data'

Thanks

**Comment by zj-zhang** [comment]
Hi @XuanrZhang thanks for catching this. I've pushed a commit to fix it 7622e2bb19b6a31a183df4c5dce404c2ce2ba3fe
Could you please pull the latest changes from the Github master branch, and see if that works for you? 
It's unfortunate that google colab dropped support for TF1.X, I'll see if there are workarounds.

**Comment by XuanrZhang** [comment]
Hi @zj-zhang Thanks for your reply. Mentioned problem is solved.
When I continued to call amb.run(), another error pops up.
------Error Message below---------
.........
 Trial 19: Start training model with sample_arc...
20:32:11 0/20, loss=0.08238
Epoch 0, loss=0.0892
16it [00:00, 38.10it/s]
W0818 20:32:45.592892 47410501705408 font_manager.py:1282] **findfont: Font family ['serif'] not found. Falling back to DejaVu Sans.**
--------------------------------------
I also noticed that the same error shows up on your [notebook page](https://colab.research.google.com/gist/zj-zhang/48689d8bdc8adf3375719911f7e41989/amber-epigenetics-tutorial-v2.ipynb#scrollTo=CFxD4Tk48ipr). (image attached)
![image](https://user-images.githubusercontent.com/18049816/185375627-d98fec31-feb9-4309-be36-8122a4417cc3.png)

I have tried lots of solutions but still didn't work. Any suggestion for solving it?

Thanks a lot.

**Comment by zj-zhang** [comment]
@XuanrZhang The warning message you show here is not an error and should not affect results from AMBER.
The warning comes from matplotlib when missing serif fonts to make a plot, but it will still make the plot with the system default font.

**Comment by XuanrZhang** [comment]
Thanks @zj-zhang, I commented the reset_style() function, it works.
